name: 'PR Up to Date'
description: 'Check if branches are up to date and merge the base branch into the pull request branch if necessary.'

inputs:
  baseBranch:
    required: true
    description: 'The base branch to compare and merge.'
    default: '${{ github.event.pull_request.base.ref }}'

  prBranch:
    required: true
    description: 'The pull request branch to compare and merge.'
    default: '${{ github.event.pull_request.head.ref }}'

  autoMerge:
    required: false
    description: 'Automatically merge the base branch into the pull request branch if necessary.'
    default: 'true'

  descriptionMerged:
    required: false
    description: 'Description of the merge commit.'
    default: 'Merge [BASE_BRANCH] into [PR_BRANCH]'

  descriptionReminder:
    required: false
    description: 'Description of the PR comment if "autoMerge" is false.'
    default: 'Please merge [BASE_BRANCH] into [PR_BRANCH].'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: fregante/setup-git-user@v2

    - name: Fetch branches and update working directory
      shell: bash
      run: |
        echo "Fetching pull request branch: ${{ inputs.prBranch }}"
        git fetch origin ${{ inputs.prBranch }}

        echo "Fetching base branch: ${{ inputs.baseBranch }}"
        git fetch origin ${{ inputs.baseBranch }}

    - name: Check if branches are up to date
      shell: bash
      id: checkBranches
      run: |
        git checkout ${{ inputs.prBranch }}
        BASE=$(git merge-base origin/${{ inputs.baseBranch }} HEAD)
        if [ $BASE = $(git rev-parse origin/${{ inputs.baseBranch }}) ]; then
          echo "Branches are up to date, skipping merge."
          echo "mergeRequired=false" >> $GITHUB_OUTPUT
        else
          echo "Branches are not up to date, merge is required."
          echo "mergeRequired=true" >> $GITHUB_OUTPUT
        fi

    - name: Build merge description
      id: merge-description
      shell: bash
      run: |
        DESCRIPTION=$(echo "${{ inputs.descriptionMerged }}" | sed "s|\[BASE_BRANCH\]|${{ inputs.baseBranch }}|g" | sed "s|\[PR_BRANCH\]|${{ inputs.prBranch }}|g")
        echo "mergeDescription=${DESCRIPTION}" >> $GITHUB_OUTPUT

    - name: Build reminder description
      id: reminder-description
      shell: bash
      run: |
        DESCRIPTION=$(echo "${{ inputs.descriptionReminder }}" | sed "s|\[BASE_BRANCH\]|${{ inputs.baseBranch }}|g" | sed "s|\[PR_BRANCH\]|${{ inputs.prBranch }}|g")
        echo "reminderDescription=${DESCRIPTION}" >> $GITHUB_OUTPUT

    - name: Merge base branch into PR branch
      shell: bash
      if: steps.checkBranches.outputs.mergeRequired == 'true' && inputs.autoMerge == 'true'
      run: |
        git merge --no-edit --no-commit origin/${{ inputs.baseBranch }}
        if [ $? -ne 0 ]; then
          echo "Merge conflict detected. Please resolve conflicts before merging."
          exit 1
        fi
        git commit -m "${{ steps.merge-description.outputs.mergeDescription }}"

    - name: Push changes
      shell: bash
      if: steps.checkBranches.outputs.mergeRequired == 'true' && inputs.autoMerge == 'true'
      run: |
        git push origin ${{ inputs.prBranch }}

    - name: Command on PR to remind the PR branch is not up to date
      if: steps.checkBranches.outputs.mergeRequired == 'true' && inputs.autoMerge == 'false'
      uses: thollander/actions-comment-pull-request@v3.0.1
      with:
        message: |
          ## This branch is out-of-date with the base branch
          ${{ steps.reminder-description.outputs.reminderDescription }}
        comment-tag: pr-up-to-date

    - name: Block the workflow if the PR branch is not up to date
      shell: bash
      if: steps.checkBranches.outputs.mergeRequired == 'true' && inputs.autoMerge == 'false'
      run: exit 1

branding:
  icon: 'git-pull-request'
  color: 'blue'
